### ISSUE TITLE
Hardware keyboard support

### ISSUE THREAD

**Issue by willem640** [jeremymarch/HCPolytonicGreekKB#1]
Hi!

I think this project should support using a hardware keyboard (bluetooth/smart connector). If you try to use it that way, you get greek characters on your keyboard, but the accent functionality disappears completely.

I currently don't have time to create a pull request myself, so I'm creating this issue so someone else can maybe work on it, and if not, I may have some spare time in the distant future.

**Comment by jeremymarch** [comment]
I looked into this a couple years ago and at the time it did not seem possible for an iOS keyboard extension to have any influence over a physical keyboard.

It does *look* like the non-accent keys transliterate the hardware keys, but I believe this is because the keyboard extension sets the language on the input fields and this causes iOS to use the iOS Greek keyboard, not the Hoplite keyboard.

I'd be very happy to be proven wrong, though, if you find anything or know of another keyboard extension which can do this.

**Comment by willem640** [comment]
I tested it and you're right. If I configure separate a Greek hardware keyboard and set it to polytonic, I can even type accents, neat!

An iOS app can detect hardware keypresses with pressesBegan, on a UIResponder object: [see here for more info](https://developer.apple.com/documentation/uikit/mac_catalyst/handling_key_presses_made_on_a_physical_keyboard)
I'm note sure if the keyboard gets any events at all, and if it's possible to intercept them to prevent numbers from appearing on the screen instead of accents
The link is for catalyst, but I think it works for normal UIKit too. It'd be quite nice to implement something like the LibreOffice plugin for the iOS/iPadOS app.

Edit: after some tinkering and searching, it seems that pressesBegan won't work (maybe because app extensions are not in the responder chain for a hardware keyboard, but I'm not sure), but GameController may work

**Comment by willem640** [comment]
After looking into it, GameController seems a bit excessive, and if it does work this is really not what Apple wants you to use app extensions for. It's a shame, but I'll have to use the polytonic Greek keyboard or preferably the on-screen keyboard for now. To be honest, I don't really mind, because the keyboard is already amazing the way it is
